SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE cart_items;
TRUNCATE TABLE wines;

ALTER TABLE wines ALTER COLUMN id RESTART WITH 1;
ALTER TABLE cart_items ALTER COLUMN id RESTART WITH 1;
SET REFERENTIAL_INTEGRITY TRUE;